version: "3.8"

services:
  flask-mijn-afval-wijzer-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - MIJN_AFVAL_WIJZER_API_KEY=
      - MINIMUM_COLLECTION_SIZE=6
    ports:
      - "8080:8080"
